config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :items do
    resources :pictures, only: [:create]
  end

  resources :carts, only: [:show, :update, :destroy, :remove_item] do
    member do
      delete 'remove_item'
    end
  end

  resources :orders
  get '/home', to: 'statics#home'
  get '/profile', to: 'orders#index'

  root 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: carts
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_carts_on_user_id  (user_id)
#

class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy
  has_many :items, through: :line_items

  def total_price
    total_price = 0
    line_items.each do |line_item|
      total_price += line_item.item.price * line_item.quantity
    end
    total_price
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:show]

  def show
    @cart = Cart.find(params[:id])
  end

  def update
    @cart = Cart.find_by(user: current_user)
    @item = Item.find(params[:id])

    add_quantity(@item)
  end

  def destroy
    @cart = Cart.find_by(user: current_user)
    @item = Item.find(params[:id])

    sub_quantity(@item)
  end

  def remove_item
    @cart = Cart.find_by(user: current_user)
    @item = Item.find(params[:id])

    flash[:notice] = "#{@item.title} has been removed." if @cart.items.delete(@item)

    redirect_back(fallback_location: root_path)
  end

  private

  def correct_user
    cart = Cart.find(params[:id])
    redirect_to root_path unless current_user == cart.user
  end

  def add_quantity(item)
    if @cart.items.include?(item)
      select_line = @cart.line_items.where(item: item)
      select_line.first.quantity += 1
      select_line.first.save
    else
      @cart.items << @item
    end

    redirect_back(fallback_location: root_path)
  end

  def sub_quantity(item)
    if @cart.line_items.where(item: item).first.quantity > 1
      select_line = @cart.line_items.where(item: item)
      select_line.first.quantity -= 1
      select_line.first.save
    else
      @cart.items.delete(item)
    end

    redirect_back(fallback_location: root_path)
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/carts/show.html.erb
<div class="container">
  <div class="row">
    <% if @cart.line_items.count > 0 %>
      <h2 class="h3 mb-3 font-weight-normal text-center">Cart</h2>
        <div class="container">
          <table class="table table-bordered">
            <thead class="thead-light">
              <tr>
                <th scope="col"></th>
                <th scope="col">Title</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
                <% @cart.line_items.each do |line| %>
                  <tr>
                    <th scope="row">
                      <%if line.item.picture.attached?%>
                          <%= image_tag(line.item.picture.variant(resize: "100x100"), alt: 'picture') %>
                      <%else%>
                          <%= image_tag('default_cat.jpg', size: "100x100") %>
                      <%end%>
                      </th>
                      <td><%= line.item.title %></td>
                      <td>€<%= line.item.price %></td>
                      <td> 
                          <!--Table-->
                          <table>
                              <!--Table body-->
                              <tbody>
                                  <tr>
                                      <td><%= button_to " - ", cart_path(line.item), method: :delete, class: "btn btn-default add-item" %></td>
                                      <td><%= line.item.line_items.where(cart_id: current_user.cart).first.quantity %></td>
                                      <td><%= button_to "+", cart_path(line.item), method: :put, class: "btn btn-default add-item" %></td>
                                  </tr>
                              </tbody>
                              <!--Table body-->
                          </table>
                          <!--Table-->
                      </td>
                      <td><%= button_to "Remove", remove_item_cart_path(line.item),method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default add-item" %>
                  </tr>
                <% end %>
                <tr>
                  <th></th>
                  <td></td>
                  <td><%= form_tag orders_path do %>
                    <article>
                      <% if flash[:error].present? %>
                        <div id="error_explanation">
                          <p><%= flash[:error] %></p>
                        </div>
                      <% end %>
                        <label class="amount">
                          <span>TOTAL PRICE : €<%= @cart.total_price %></span>
                        </label>
                    </article>
                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                            data-description="Payment order"
                            data-amount="<%= @cart.total_price * 100 %>"
                            data-currency="eur"
                            data-locale="auto">
                    </script>
                    <% end %>
                    </td>
                  </tr>
            </tbody>
          </table>
        </div>
    <% else %>
      <p class="h3 mb-3 text-center">Your cart is empty.</p>
      <p class="text-center">Your cart is currently empty. Return to our shop and check out the latest offers. We have some great items that are waiting for you.</p>
    <% end %>
    <p class="h3 mb-3 font-weight-normal text-center"><%= link_to "Go shopping", root_path, class: "btn btn-primary" %></p>
  </div>
</div>