config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :items do
    resources :pictures, only: [:create]
  end

  resources :carts, only: [:show, :update, :destroy, :remove_item] do
    member do
      delete 'remove_item'
    end
  end

  resources :orders
  get '/home', to: 'statics#home'
  get '/profile', to: 'orders#index'

  root 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.erb
<% if notice %>
	<div class='alert alert-success p-2'>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger p-2'>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="section section-min">
		<footer class="footer">
			<div class="container">
				<div class="row">
					<div class="col-md-4 col-md-push-4 text-center"> <img class="footer-logo" src="https://i.pinimg.com/736x/1a/34/5c/1a345cdb8ba185c029a94763cd72ee49.jpg" alt="footer-logo">
						<div class="social">
							<ul>
								<li><a href="http://facebook.com/" target="_blank"><span class="ti-facebook"></span></a></li>
								<li><a href="https://twitter.com/" target="_blank"><span class="ti-twitter-alt"></span></a></li>
								<li><a href="http://linkedin.com/" target="_blank"><span class="ti-linkedin"></span></a></li>
								<li><a href="https://vimeo.com/" target="_blank"><span class="ti-vimeo-alt"></span></a></li>
								<li><a href="http://youtube.com/" target="_blank"><span class="ti-youtube"></span></a></li>
							</ul>
						</div>
					</div>
					<div class="clearfix"></div>
					<div class="col-md-4 col-md-offset-4 col-sm-12">
						<div class="footer-newsletter">
							<div class="center text-center">
								<h4>stay tuned</h4>
								<form action="#" method="post">
									<div class="input-group">
										<input class="form-control" type="text" placeholder="e-mail"> 
										<span class="input-group-btn">
											<button class="btn btn-default" type="button"><span class="ti-arrow-right"></span></button>
										</span>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>

app/views/layouts/_header.html.erb
<div class="container-fluid">
	<div class="navbar-header">
		<button class="navbar-toggle" data-target="#myNavbar" data-toggle="collapse" type="button">
			<span class="icon-bar"></span> 
			<span class="icon-bar"></span> 
			<span class="icon-bar"></span>
		</button>
		
		<a class="navbar-brand" href="<%= root_path %>"> <img src="https://i.pinimg.com/736x/1a/34/5c/1a345cdb8ba185c029a94763cd72ee49.jpg" alt="logo"></a>
	</div>
	<div class="collapse navbar-collapse" id="myNavbar">
		<ul class="nav navbar-nav">
			<li><a href="<%= root_path %>">home</a></li>
			<li><a href="<%= root_path %>">products</a></li>
			<% if user_signed_in? %>
				<li>
					<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
				</li>
				<li>
					<%= link_to "My profile", profile_path %>
				</li>
			<% else %>
				<li>    
					<%= link_to "Sign in", new_user_session_path %>
				</li>
				<li>
				<%= link_to "Sign up", new_user_registration_path %>
				</li>
			<% end %>
			<li class="nav-item active">
                <%= link_to 'New Item', new_item_path, class: "nav-link" %>
            </li>
			<% if current_user %>
				<li class="nav-item active">
					<%= link_to cart_path(current_user.cart) do %> 
					<%= image_tag('cart_image.png', size: "20x20") %>
					<%= current_user.cart.line_items.sum(&:quantity) %>
					<% end %>           
				</li>
			<% end %>
		</ul>
	</div>
</div>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>